# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no

  tasks:
  - name: Install mongodb package
    debug:
      msg: "В этом сценарии нужно добавить модули для установки mongodb, после можно удалить вызов модуля debug, который выводит это сообщение"
  
  - name: Add Mongo packages repo apt key
    sudo: yes
    apt_key: id=2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5  keyserver=hkp://keyserver.ubuntu.com:80

  - name: add repo itself
    sudo: yes
    apt_repository: repo='deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse' state=present                                      

  - name: Update and upgrade apt packages
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install packages
    sudo: yes
    apt: pkg=mongodb-org state=present

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: reddit_app
  gather_facts: no

  tasks:
  - name: Remove me after adding real things
    debug:
      msg: "В этом сценарии нужно добавить модули для деплоя приложения, после можно удалить вызов модуля debug, который выводит это сообщение"
  - git: >
      repo=https://github.com/tmarkunin/infra.git
      dest=~/infra
      version: ansible-1

  - name: Install bundle
    bundler:
    state: present
    gemfile: ~/infra/Gemfile
